# Sending Emails with Images
# import the necessary components first
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import base64

# server and port
smtp_server = "smtp.mailtrap.io"
port = 2525

# your login credentials generated by Mailtrap
login = "<your user_id>"
password = "<your password>"

# sender and receiver emails
sender = "sender@example.com"
receiver = "receiver@example.com"

# message object
message = MIMEMultipart("alternative")
message["Subject"] = "Python Logo in Email"
message["From"] = sender
message["To"] = receiver

# read and encode the image file
encoded_image = base64.b64encode(open("images/python_logo.jpeg", "rb").read()).decode()

html = f"""\
<html>
 <body>
    <h1>This is an email with image in it</h1> <br>
   <img src="data:image/jpg;base64,{encoded_image}">
 </body>
</html>
"""

# set MIME type and attach it to the message
part = MIMEText(html, "html")
message.attach(part)

# send the email
with smtplib.SMTP(smtp_server, port) as server:
    try:
        server.login(login, password)
        server.sendmail(sender, receiver, message.as_string())
    except Exception as ex:
        print(ex)
    else:
        print("Email with Image sent successfully...")

