# Sending HTML Email

# import smtplib and email.mime classes
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# define the port
port = 2525

# SMTP server
smtp_server = "smtp.mailtrap.io"

# login credentials
# paste your login generated by Mailtrap
login = "<your user_id>"
# paste your password generated by Mailtrap
password = "<your password>"

# sender and receiver emails
sender = "sender@example.com"
receiver = "receiver@example.com"

# message object
message = MIMEMultipart("alternative")
message["Subject"] = "HTML Mail Test with multipart"
message["From"] = sender
message["To"] = receiver

# --- PLAIN TEXT PART ---
with open("files/plain_text_part.txt") as plain_text_part:
    text = plain_text_part.read()

# --- HTML PART ---
with open("files/html_part.txt") as html_part:
    html = html_part.read()

# convert both parts to MIMEText objects
part1 = MIMEText(text, "plain")
part2 = MIMEText(html, "html")

# add the parts to the MIMEMultipart message
message.attach(part1)
message.attach(part2)

# send your email
with smtplib.SMTP(smtp_server, port) as server:
    try:
        server.login(login, password)
        server.sendmail(sender, receiver, message.as_string())
    except Exception as ex:
        print(ex)
    else:
        print("Multipart Message sent successfully...")

